---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
    aws cloudformation validate-template --template-body file://$(pwd)/ami.yaml
    aws cloudformation create-stack --stack-name VladStack --template-body file://$(pwd)/ami.yaml --parameters ParameterKey=UserData,ParameterValue=$(base64 -w0 ec2-user-data.sh)
    aws cloudformation update-stack --stack-name VladStack --template-body file://$(pwd)/ami.yaml --parameters ParameterKey=UserData,ParameterValue=$(base64 -w0 ec2-user-data.sh)
    aws cloudformation delete-stack --stack-name VladStack
Parameters:
    ImageId:
        Description: EC2 image ID
        Type: String
        Default: ami-0eaec5838478eb0ba
    InstanceType:
        Description: EC2 instance type
        Type: String
        Default: t2.micro
    KeyName:
        Description: SSH key name to access EC2
        Type: String
        Default: vprokopy
    UserData:
        Description: EC2 UserData Bash startup script
        Type: String
Resources:
    # VPC
    Vpc:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.1.0.0/16
            EnableDnsSupport: true
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: !Join ["", [!Ref "AWS::StackName", "-VPC"]]
    # Public Subnet
    PublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref Vpc
            CidrBlock: 10.1.10.0/24
            AvailabilityZone: !Select [0, !GetAZs ]
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName}-Public
    # InternetGateway
    InternetGateway:
        Type: AWS::EC2::InternetGateway
    GatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref Vpc
            InternetGatewayId: !Ref InternetGateway
    # Public RouteTable
    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref Vpc
            Tags:
                - Key: Name
                  Value: Public
    PublicRoute1:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway
    PublicSubnetRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet
    # Public SecurityGroup
    PublicSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: PublicSecurityGroup
            GroupDescription: Public Security Group
            VpcId: !Ref Vpc
    PublicOutboundRule1:
        Type: AWS::EC2::SecurityGroupEgress
        Properties:
            GroupId: !Ref PublicSecurityGroup
            IpProtocol: "-1"
            FromPort: 0
            ToPort: 65535
            CidrIp: 0.0.0.0/0
    PublicInboundRule1:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref PublicSecurityGroup
            IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
    PublicInboundRule2:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref PublicSecurityGroup
            IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
    # Public EC2
    PublicEc2:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref ImageId
            InstanceType: !Ref InstanceType
            KeyName: !Ref KeyName
            UserData: !Ref UserData
            SecurityGroupIds:
                - !GetAtt PublicSecurityGroup.GroupId
            SubnetId: !Ref PublicSubnet
            Tags:
                - Key: Name
                  Value: PublicEc2
Outputs:
    # VPC
    VpcId:
        Description: VPC ID
        Value: !Ref Vpc
    VpcCidrBlock:
        Description: VPC CIDR block
        Value: !GetAtt Vpc.CidrBlock
    # Public Subnet
    PublicSubnetId:
        Description: Public Subnet ID
        Value: !Ref PublicSubnet
    PublicSubnetAvailabilityZone:
        Description: Public Subnet AvailabilityZone
        Value: !GetAtt PublicSubnet.AvailabilityZone
    InternetGatewayId:
        Description: InternetGateway ID
        Value: !Ref InternetGateway
    # Public SecurityGroup
    PublicSecurityGroupId:
        Description: Public SecurityGroup ID
        Value: !Ref PublicSecurityGroup
    # Public EC2
    PublicEc2InstanceId:
        Description: Public EC2 instance ID
        Value: !Ref PublicEc2
    PublicEc2PublicDnsName:
        Description: Public EC2 public DNS name
        Value: !GetAtt PublicEc2.PublicDnsName
    PublicEc2PublicIp:
        Description: Public EC2 public IP
        Value: !GetAtt PublicEc2.PublicIp
    PublicEc2PrivateDnsName:
        Description: Public EC2 private DNS name
        Value: !GetAtt PublicEc2.PrivateDnsName
    PublicEc2PrivateIp:
        Description: Public EC2 private IP
        Value: !GetAtt PublicEc2.PrivateIp
