---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
    Create Kinesis Firehose delivery streams with associated S3 bucket
Parameters:
    # S3
    S3InfringementDeliveryBucketName:
        Description: Kinesis Firehose infringement delivery S3 bucket name
        Type: String
    S3InfringementDeliveryObjectExpirationInDays:
        Description: Kinesis Firehose infringement delivery S3 object expiration in days
        Type: Number
        Default: 60
    # Kinesis Firehose
    FirehoseBufferSizeMbs:
        Description: Kinesis Firehose buffer size in MBs
        Type: Number
        Default: 1
    FirehoseBufferIntervalSecs:
        Description: Kinesis Firehose buffer interval in seconds
        Type: Number
        Default: 60
    CloudWatchInfringementDeliveryLogRetentionDays:
        Description: Kinesis Firehose log retention period in days
        Type: Number
        Default: 30
Resources:
    # Kinesis Firehose delivery stream S3 bucket
    S3InfringementDeliveryBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete # Retain
        Properties:
            BucketName: !Ref S3InfringementDeliveryBucketName
            LifecycleConfiguration:
                Rules:
                    - Id: InfringementDeliveryObjectExpiration
                      Status: Enabled
                      ExpirationInDays: !Ref S3InfringementDeliveryObjectExpirationInDays
    # Kinesis Firehose CloudWatch log group
    CloudWatchInfringementDeliveryLogGroup:
        Type: AWS::Logs::LogGroup
        DeletionPolicy: Delete # Retain
        Properties:
            LogGroupName: !Sub /aws/kinesisfirehose/${AWS::StackName}-InfringementDeliveryLogGroup
            RetentionInDays: !Ref CloudWatchInfringementDeliveryLogRetentionDays
    # Product delivery log stream
    CloudWatchProductDeliveryLogStream:
        Type: AWS::Logs::LogStream
        Properties:
            LogGroupName: !Ref CloudWatchInfringementDeliveryLogGroup
            LogStreamName: !Sub ${AWS::StackName}-ProductDeliveryLogStream
    # Infringement delivery log stream
    CloudWatchInfringementDeliveryLogStream:
        Type: AWS::Logs::LogStream
        Properties:
            LogGroupName: !Ref CloudWatchInfringementDeliveryLogGroup
            LogStreamName: !Sub ${AWS::StackName}-InfringementDeliveryLogStream
    # Kinesis Firehose IAM Role
    IamInfringementDeliveryPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            ManagedPolicyName: !Sub ${AWS::StackName}-IamInfringementDeliveryPolicy
            Description: >-
                Grants access to Kinesis Firehose infringement delivery streams to put
                data into S3 bucket
            Path: /
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    # S3
                    - Effect: Allow
                      Action:
                          - s3:GetBucketLocation
                          - s3:ListBucket
                          - s3:PutObject
                          - s3:ListBucketMultipartUploads
                          - s3:AbortMultipartUpload
                      Resource:
                          - !GetAtt S3InfringementDeliveryBucket.Arn
                          - !Sub ${S3InfringementDeliveryBucket.Arn}/*
                    # CloudWatch
                    - Effect: Allow
                      Action:
                          - logs:*
                      Resource:
                          - arn:aws:logs:*:*:*
    IamInfringementDeliveryRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub ${AWS::StackName}-IamInfringementDeliveryRole
            Path: /
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action:
                          - sts:AssumeRole
                      Principal:
                          Service:
                              - firehose.amazonaws.com
            ManagedPolicyArns:
                - !Ref IamInfringementDeliveryPolicy
    # Kinesis Firehose product delivery stream
    FirehoseProductDeliveryStream:
        Type: AWS::KinesisFirehose::DeliveryStream
        Properties:
            DeliveryStreamName: !Sub ${AWS::StackName}-ProductDeliveryStream
            DeliveryStreamType: DirectPut
            S3DestinationConfiguration:
                BucketARN: !GetAtt S3InfringementDeliveryBucket.Arn
                BufferingHints:
                    SizeInMBs: !Ref FirehoseBufferSizeMbs
                    IntervalInSeconds: !Ref FirehoseBufferIntervalSecs
                CompressionFormat: UNCOMPRESSED
                Prefix: product/
                ErrorOutputPrefix: product-error/
                RoleARN: !GetAtt IamInfringementDeliveryRole.Arn
                CloudWatchLoggingOptions:
                    Enabled: true
                    LogGroupName: !Ref CloudWatchInfringementDeliveryLogGroup
                    LogStreamName: !Ref CloudWatchProductDeliveryLogStream
    # Kinesis Firehose infringement delivery stream
    FirehoseInfringementDeliveryStream:
        Type: AWS::KinesisFirehose::DeliveryStream
        Properties:
            DeliveryStreamName: !Sub ${AWS::StackName}-InfringementDeliveryStream
            DeliveryStreamType: DirectPut
            S3DestinationConfiguration:
                BucketARN: !GetAtt S3InfringementDeliveryBucket.Arn
                BufferingHints:
                    SizeInMBs: !Ref FirehoseBufferSizeMbs
                    IntervalInSeconds: !Ref FirehoseBufferIntervalSecs
                CompressionFormat: UNCOMPRESSED
                Prefix: infringement/
                ErrorOutputPrefix: infringement-error/
                RoleARN: !GetAtt IamInfringementDeliveryRole.Arn
                CloudWatchLoggingOptions:
                    Enabled: true
                    LogGroupName: !Ref CloudWatchInfringementDeliveryLogGroup
                    LogStreamName: !Ref CloudWatchInfringementDeliveryLogStream
Outputs:
    # Kinesis Firehose delivery streams S3 bucket
    S3InfringementDeliveryBucketName:
        Description: Kinesis Firehose infringement delivery S3 bucket name
        Value: !Ref S3InfringementDeliveryBucket
    S3InfringementDeliveryBucketArn:
        Description: Kinesis Firehose infirngement delivery S3 bucket ARN
        Value: !GetAtt S3InfringementDeliveryBucket.Arn
        Export:
            Name: !Sub ${AWS::StackName}:S3InfringementDeliveryBucketArn
    # Kinesis Firehose product delivery stream
    FirehoseProductDeliveryStreamName:
        Description: Kineis Firehose product delivery stream name
        Value: !Ref FirehoseProductDeliveryStream
        Export:
            Name: !Sub ${AWS::StackName}:ProductDeliveryStreamName
    # Kinesis Firehose infringement delivery stream
    FirehoseInfringementDeliveryStreamName:
        Description: Kinesis Firehose infringement delivery stream name
        Value: !Ref FirehoseInfringementDeliveryStream
        Export:
            Name: !Sub ${AWS::StackName}:InfringementDeliveryStreamName
