---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
    Create Kinesis Firehose delivery streams with associated S3 bucket
Parameters:
    # S3
    S3FirehoseInfringementDeliveryBucketName:
        Description: Kinesis Firehose infringement delivery S3 bucket suffix
        Type: String
    # Kinesis Firehose
    FirehoseInfringementDeliveryLogRetentionDays:
        Description: Kinesis Firehose log retention period in days
        Type: Number
        Default: 7
    FirehoseBufferSizeMb:
        Description: Kinesis Firehose buffer size in MB
        Type: Number
        Default: 1
    FirehoseBufferIntervalSec:
        Description: Kinesis Firehose buffer interval in sec
        Type: Number
        Default: 60
Resources:
    # Kinesis Firehose delivery stream S3 bucket
    S3FirehoseInfringementDeliveryBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: !Ref S3FirehoseInfringementDeliveryBucketName
    # Kinesis Firehose CloudWatch log group and log streams
    FirehoseInfringementDeliveryLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub /aws/kinesisfirehose/${AWS::StackName}-InfringementDeliveryLogGroup
            RetentionInDays: !Ref FirehoseInfringementDeliveryLogRetentionDays
    # Product delivery log stream
    ProductDeliveryLogStream:
        Type: AWS::Logs::LogStream
        Properties:
            LogGroupName: !Ref FirehoseInfringementDeliveryLogGroup
            LogStreamName: !Sub ${AWS::StackName}-ProductDeliveryLogStream
    # Infringement delivery log stream
    InfringementDeliveryLogStream:
        Type: AWS::Logs::LogStream
        Properties:
            LogGroupName: !Ref FirehoseInfringementDeliveryLogGroup
            LogStreamName: !Sub ${AWS::StackName}-InfringementDeliveryLogStream
    # Kinesis Firehose IAM Role
    IamFirehoseInfringementDeliveryPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            ManagedPolicyName: !Sub ${AWS::StackName}-IamFirehoseInfringementDeliveryPolicy
            Description: >-
                Grants access to Kinesis Firehose infringement delivery streams to put
                data into S3 bucket
            Path: /
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    # S3
                    - Effect: Allow
                      Action:
                          - s3:GetBucketLocation
                          - s3:ListBucket
                          - s3:PutObject
                          - s3:ListBucketMultipartUploads
                          - s3:AbortMultipartUpload
                      Resource:
                          - !GetAtt S3FirehoseInfringementDeliveryBucket.Arn
                          - !Sub ${S3FirehoseInfringementDeliveryBucket.Arn}/*
                    # CloudWatch
                    - Effect: Allow
                      Action:
                          - logs:*
                      Resource:
                          - arn:aws:logs:*:*:*
    IamFirehoseInfringementDeliveryRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: !Sub ${AWS::StackName}-IamFirehoseInfringementDeliveryRole
            Path: /
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Action:
                          - sts:AssumeRole
                      Principal:
                          Service:
                              - firehose.amazonaws.com
            ManagedPolicyArns:
                - !Ref IamFirehoseInfringementDeliveryPolicy
    # Kinesis Firehose product delivery stream
    ProductDeliveryStream:
        Type: AWS::KinesisFirehose::DeliveryStream
        Properties:
            DeliveryStreamName: !Sub ${AWS::StackName}-ProductDeliveryStream
            DeliveryStreamType: DirectPut
            S3DestinationConfiguration:
                BucketARN: !GetAtt S3FirehoseInfringementDeliveryBucket.Arn
                BufferingHints:
                    SizeInMBs: !Ref FirehoseBufferSizeMb
                    IntervalInSeconds: !Ref FirehoseBufferIntervalSec
                CompressionFormat: UNCOMPRESSED
                Prefix: product/
                ErrorOutputPrefix: product-error/
                RoleARN: !GetAtt IamFirehoseInfringementDeliveryRole.Arn
                CloudWatchLoggingOptions:
                    Enabled: true
                    LogGroupName: !Ref FirehoseInfringementDeliveryLogGroup
                    LogStreamName: !Ref ProductDeliveryLogStream
    # Kinesis Firehose infringement delivery stream
    InfringementDeliveryStream:
        Type: AWS::KinesisFirehose::DeliveryStream
        Properties:
            DeliveryStreamName: !Sub ${AWS::StackName}-InfringementDeliveryStream
            DeliveryStreamType: DirectPut
            S3DestinationConfiguration:
                BucketARN: !GetAtt S3FirehoseInfringementDeliveryBucket.Arn
                BufferingHints:
                    SizeInMBs: !Ref FirehoseBufferSizeMb
                    IntervalInSeconds: !Ref FirehoseBufferIntervalSec
                CompressionFormat: UNCOMPRESSED
                Prefix: infringement/
                ErrorOutputPrefix: infringement-error/
                RoleARN: !GetAtt IamFirehoseInfringementDeliveryRole.Arn
                CloudWatchLoggingOptions:
                    Enabled: true
                    LogGroupName: !Ref FirehoseInfringementDeliveryLogGroup
                    LogStreamName: !Ref InfringementDeliveryLogStream
Outputs:
    # Kinesis Firehose delivery stream S3 bucket
    S3FirehoseInfringementDeliveryBucketName:
        Description: Kinesis Firehose infringement delivery S3 bucket name
        Value: !Ref S3FirehoseInfringementDeliveryBucket
    S3FirehoseInfringementDeliveryBucketArn:
        Description: Kinesis Firehose infirngement delivery S3 bucket ARN
        Value: !GetAtt S3FirehoseInfringementDeliveryBucket.Arn
        Export:
            Name: !Sub ${AWS::StackName}:S3FirehoseInfringementDeliveryBucketArn
    # Kinesis Firehose product delivery stream
    ProductDeliveryStreamName:
        Description: Kineis product delivery stream name
        Value: !Ref ProductDeliveryStream
        Export:
            Name: !Sub ${AWS::StackName}:ProductDeliveryStreamName
    # Kinesis Firehose infringement delivery stream
    InfringementDeliveryStreamName:
        Description: Kinesis infringement delivery stream name
        Value: !Ref InfringementDeliveryStream
        Export:
            Name: !Sub ${AWS::StackName}:InfringementDeliveryStreamName
